# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportMonitor_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 313)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("LELIEL.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_feedback = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_feedback.setFont(font)
        self.label_feedback.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_feedback.setTextFormat(QtCore.Qt.AutoText)
        self.label_feedback.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback.setObjectName("label_feedback")
        self.gridLayout.addWidget(self.label_feedback, 7, 0, 1, 4)
        self.label_captcha = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_captcha.setFont(font)
        self.label_captcha.setTextFormat(QtCore.Qt.AutoText)
        self.label_captcha.setObjectName("label_captcha")
        self.gridLayout.addWidget(self.label_captcha, 2, 3, 1, 1)
        self.label_student_id = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_student_id.setFont(font)
        self.label_student_id.setTextFormat(QtCore.Qt.AutoText)
        self.label_student_id.setObjectName("label_student_id")
        self.gridLayout.addWidget(self.label_student_id, 2, 0, 1, 1)
        self.button_save_account = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_account.setObjectName("button_save_account")
        self.gridLayout.addWidget(self.button_save_account, 3, 3, 1, 1)
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.line_password.setObjectName("line_password")
        self.gridLayout.addWidget(self.line_password, 3, 1, 1, 1)
        self.line_student_id = QtWidgets.QLineEdit(self.centralwidget)
        self.line_student_id.setObjectName("line_student_id")
        self.gridLayout.addWidget(self.line_student_id, 2, 1, 1, 1)
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_password.setFont(font)
        self.label_password.setTextFormat(QtCore.Qt.AutoText)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 3, 0, 1, 1)
        self.label_captcha_pic = QtWidgets.QLabel(self.centralwidget)
        self.label_captcha_pic.setMinimumSize(QtCore.QSize(64, 28))
        self.label_captcha_pic.setMaximumSize(QtCore.QSize(64, 28))
        self.label_captcha_pic.setText("")
        self.label_captcha_pic.setObjectName("label_captcha_pic")
        self.gridLayout.addWidget(self.label_captcha_pic, 2, 7, 1, 1)
        self.button_connect = QtWidgets.QPushButton(self.centralwidget)
        self.button_connect.setObjectName("button_connect")
        self.gridLayout.addWidget(self.button_connect, 6, 0, 1, 1)
        self.check_auto = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.check_auto.setFont(font)
        self.check_auto.setObjectName("check_auto")
        self.gridLayout.addWidget(self.check_auto, 3, 7, 1, 1)
        self.label_promote = QtWidgets.QLabel(self.centralwidget)
        self.label_promote.setObjectName("label_promote")
        self.gridLayout.addWidget(self.label_promote, 8, 0, 2, 8)
        self.line_captcha = QtWidgets.QLineEdit(self.centralwidget)
        self.line_captcha.setObjectName("line_captcha")
        self.gridLayout.addWidget(self.line_captcha, 2, 5, 1, 2)
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setObjectName("button_start")
        self.gridLayout.addWidget(self.button_start, 3, 5, 1, 2)
        self.button_block_list = QtWidgets.QPushButton(self.centralwidget)
        self.button_block_list.setObjectName("button_block_list")
        self.gridLayout.addWidget(self.button_block_list, 6, 6, 1, 1)
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setObjectName("button_stop")
        self.gridLayout.addWidget(self.button_stop, 6, 5, 1, 1)
        self.check_toast = QtWidgets.QCheckBox(self.centralwidget)
        self.check_toast.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.check_toast.setFont(font)
        self.check_toast.setChecked(True)
        self.check_toast.setObjectName("check_toast")
        self.gridLayout.addWidget(self.check_toast, 6, 7, 1, 1)
        self.text_info_board = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_info_board.setObjectName("text_info_board")
        self.gridLayout.addWidget(self.text_info_board, 7, 5, 1, 2)
        self.label_connection_status = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_connection_status.setFont(font)
        self.label_connection_status.setObjectName("label_connection_status")
        self.gridLayout.addWidget(self.label_connection_status, 6, 1, 1, 2)
        self.label_to_website = QtWidgets.QLabel(self.centralwidget)
        self.label_to_website.setAlignment(QtCore.Qt.AlignCenter)
        self.label_to_website.setObjectName("label_to_website")
        self.gridLayout.addWidget(self.label_to_website, 6, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_report = QtWidgets.QAction(MainWindow)
        self.menu_report.setCheckable(True)
        self.menu_report.setChecked(True)
        self.menu_report.setObjectName("menu_report")
        self.menu_lesson = QtWidgets.QAction(MainWindow)
        self.menu_lesson.setCheckable(True)
        self.menu_lesson.setObjectName("menu_lesson")
        self.menu.addAction(self.menu_report)
        self.menu.addAction(self.menu_lesson)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.line_student_id, self.line_password)
        MainWindow.setTabOrder(self.line_password, self.line_captcha)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ReportMonitor"))
        self.label_feedback.setText(_translate("MainWindow", "提示信息"))
        self.label_captcha.setText(_translate("MainWindow", "验证码："))
        self.label_student_id.setText(_translate("MainWindow", "学号："))
        self.button_save_account.setText(_translate("MainWindow", "设为默认帐号"))
        self.label_password.setText(_translate("MainWindow", "密码："))
        self.button_connect.setText(_translate("MainWindow", "连接网站"))
        self.check_auto.setText(_translate("MainWindow", "托管"))
        self.label_promote.setText(_translate("MainWindow", "<html><head/><body><p>内部使用</p></body></html>"))
        self.button_start.setText(_translate("MainWindow", "开始"))
        self.button_block_list.setText(_translate("MainWindow", "屏蔽列表"))
        self.button_stop.setText(_translate("MainWindow", "停止"))
        self.check_toast.setText(_translate("MainWindow", "通知"))
        self.label_connection_status.setText(_translate("MainWindow", "未连接"))
        self.label_to_website.setText(_translate("MainWindow", "<A href=\'http://yjsy.buct.edu.cn:8080/pyxx/login.aspx\'>研究生管理系统</a>"))
        self.menu.setTitle(_translate("MainWindow", "监测任务"))
        self.menu_report.setText(_translate("MainWindow", "ReportMonitor"))
        self.menu_lesson.setText(_translate("MainWindow", "Lesson"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

